version: 2

updates:
- package-ecosystem: "pip"
  directory: "/"
  target-branch: "dev"
  schedule:
    interval: "weekly"
  groups:
    safe:
      update-types:
        - "minor"
        - "patch"
    major:
      update-types:
        - "major"
