from typing import Iterable, TypeVar, overload

_T = TypeVar("_T")

def get_instance(reference: type[_T]) -> _T: ...
def inject(*): ...
def injectable(*, reference: type = ...): ...
@overload
def injectable(*, references: Iterable[type] = ...): ...
def singleton(*, reference: type = ...): ...
@overload
def singleton(*, references: Iterable[type] = ...): ...
