name: Code Style
description: Check code style
runs:
  using: "composite"
  steps:
    - name: Isort
      shell: bash
      run: isort ./ --check

    - name: Black
      shell: bash
      run: black ./ --check

    - name: Flake8
      shell: bash
      run: flake8
