name: Code Style
description: Check code style

runs:
  using: "composite"
  steps:
    - name: Ruff
      shell: bash
      run: |
        ruff format --check
        ruff check

    - name: MyPy
      if: "false"  # TODO: Put it back when Python `3.12` is supported
      shell: bash
      run: mypy ./
