name: Deploy
description: Publish package on PyPI
runs:
  using: "composite"
  steps:
    - name: Publish
      shell: bash
      run: |
        poetry version ${{ env.VERSION }}
        poetry publish --build
