name: Deploy
description: Publish package on PyPI
runs:
  using: "composite"
  steps:
    - name: Prepare Poetry
      shell: bash
      run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

    - name: Publish
      shell: bash
      run: |
        poetry version ${{ github.ref_name }}
        poetry publish --build
