name: CD

on:
  push:
    tags:
      - "^([1-9]\d*!)?(0|[1-9]\d*)(\.(0|[1-9]\d*))*((a|b|rc)(0|[1-9]\d*))?(\.post(0|[1-9]\d*))?(\.dev(0|[1-9]\d*))?$"

jobs:
  cd:
    name: Continuous Delivery
    runs-on: ubuntu-latest

    steps:
      - name: Run checkout
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/environment

      - name: Deploy
        uses: ./.github/actions/deploy
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
          VERSION: ${{ github.ref_name }}
