name: GitHub Pages

on:
  push:
    branches:
      - prod

jobs:
  delivery:
    name: Delivery
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Run checkout
        uses: actions/checkout@v7

      - name: Configure Git
        run: |
          git config --global user.name "github-pages[bot]"
          git config --global user.email "github-pages[bot]@users.noreply.github.com"

      - name: Set up environment
        uses: ./.github/actions/environment

      - name: Build Zensical
        shell: bash
        run: uv run zensical build --clean

      - name: Deploy to GitHub Pages
        shell: bash
        run: uv run ghp-import --branch gh-pages --force --message "Deployed ${GITHUB_SHA} with Zensical" --no-jekyll --push site
